#!/bin/bash
# Description:
#   Sets up Bobby's NextStep Marketplace workspace and provides custom workspace functions.
# Author:
#   Robert Colley
# Date:
#   7/10/19

## Parameter Checking

## Variable Declarations
WORKFLOWS="/Users/robertcolley/.bin/workflows/"

## Function Declarations
# helper function to print script results to output file
# arg 1 is the page to start the server on.
function start() {
  # open the project 
  open ios/hey-nextstep.xcworkspace

  # start the 6s simulator
  xcrun simctl boot 13502CBC-0588-4BC2-A532-20DC5F767B2C

  # start the expo server
  expo start
  return 0
}

function close() {
  # reset everything here
  cd
  clear

  # print the seconds out
  duration=$SECONDS
  echo "$(($duration / 60)) minutes and $(($duration % 60)) seconds elapsed. Good work!"
  SECONDS=0

  # close all the open windows except the terminal window
  automator ${WORKFLOWS}EndWorkspaceSession.workflow &> /dev/null


  # resets the shell 
  source ~/.zshrc

  # unset the workspace functions
  unset -f start
  unset -f close

  reset
  return 0
}

## Main Code
# enter project directory
cd $ns/Hey-NextStep

# open slack
open -a slack

# open firefox
open -a firefox

# open atom to the project
atom .
