#!/bin/bash
# Description:
#   Sets up Bobby's NextStep Marketplace workspace and provides custom workspace functions.
# Author:
#   Robert Colley
# Date:
#   7/10/19

## Parameter Checking

## Variable Declarations
WORKFLOWS="/Users/robertcolley/.bin/workflows/"

## Function Declarations
# helper function to print script results to output file
# arg 1 is the page to start the server on.
function start() {
  echo "Staring NexStep Marketplace Server."
  if [ $# -eq 0 ] || [[ $pages =~ (^|[[:space:]])"${1}"($|[[:space:]]) ]]; then
    open -a firefox -g "http://localhost:3000/${1}"
  else
    echo "Page ${1} not found."
    open -a firefox -g "http://localhost:3000/"
  fi
  automator "${WORKFLOWS}/FirefoxFocus.workflow"  &> /dev/null
  npm run dev
  return 0
}

function close() {
  # reset everything here
  cd
  clear

  # print the seconds out
  duration=$SECONDS
  echo "$(($duration / 60)) minutes and $(($duration % 60)) seconds elapsed. Good work!"
  SECONDS=0

  # close all the open windows except the terminal window
  automator "${WORKFLOWS}EndWorkspaceSession.workflow" &> /dev/null

  # resets the shell 
  source ~/.zshrc

  # unset workspace functions
  unset -f start
  unset -f close
  reset
  return 0
}

## Main Code
# enter project directory
cd $ns/nextstep-marketplace
pages=$(ls -d pages/*/ | cut -d '/' -f 2)

# completions
complete -W "$pages" start

# open slack
open -a slack

# open firefox
open -a firefox

# open atom to the project
atom .
